pipeline {
    agent any
    
    environment {
        RELEASE_DIR = 'release'
    }
    
    stages {
        stage('Build') {
            steps {
                dir('BHD.Services/BHD.LogsHut') {
                    script {
                        sh 'ls'
                        sh 'dotnet restore'
                        sh 'dotnet build -c Release'  // Specify the Release configuration
                    }
                }
            }
        }

        stage('Package') {
            steps {
                dir('BHD.Services/BHD.LogsHut') {
                    script {
                        // Create a directory for the release artifacts
                        sh "mkdir -p ${env.RELEASE_DIR}"

                        // Publish the application for deployment
                        sh "dotnet publish -c Release -o ${env.RELEASE_DIR}"
                    }
                }
                dir('BHD.Services/BHD.LogsHut'){
                    script {
                        // Your build and packaging steps go here

                        def releaseContent = sh(script: "ls ${env.RELEASE_DIR}", returnStdout: true).trim()
                        echo "Release content: ${releaseContent}"
                    }
                }
            }
        }
    }
    
    post {
        // Your build and packaging steps go here
        success {
            echo 'Build and packaging successful!'
            
            // Archive the artifacts
            dir('BHD.Services/BHD.LogsHut'){
                archiveArtifacts artifacts: "${env.RELEASE_DIR}/*", allowEmptyArchive: true
            }            
        }
        failure {
            echo 'Build failed!'
        }
    }
}