pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                dir('BHD.Services/BHD.Logger') {
                    script {
                        sh 'ls'
                        sh 'dotnet restore'
                        sh 'dotnet build'
                    }
                }
            }
        }
    }
    
    post {
        success {
            echo 'Build successful!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}