pipeline {
    agent any
    
    stages {
        stage('Do Nothing') {
            steps {
                echo 'Logging before SCM checkout'
            }
        }
    }
    
    post {
        always {
            echo 'Some bla lba'
        }
    }
}